version: "3.8"
services:

  db:
    image: postgres:latest
    network_mode: bridge
    container_name: bookShop
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo
    restart: unless-stopped

volumes:
  pgdata: